### PR TITLE
CB-13680: (ios) First check for NSLocationAlwaysUsageDescription permission to make sure requestAlwaysAuthorization is fired instead of requestWhenInUseAuthorization

### PR DESCRIPTION
**Pull request by Babettestam**
### Platforms affected
iOS

### What does this PR do?
Reverses the check for location permissions in iOS, so the requestAlwaysAuthorization is possible in newest iOS versions.

### What testing has been done on this change?
Only testen a Cordova app that contains the NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription. The app asks the user if it wants to give the application permission to access the location "Only While Using The App", "Always Allow" or "Don't Allow".

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by edvenkat** [comment]
When it is in live???? or we can use "https://github.com/Babettestam/cordova-plugin-geolocation" this url

**Comment by ToniKorin** [comment]
Please could you accept this change to the official release? It is a critical change for iOS 11.
Cheers,
Toni

**Comment by komodo-solutions** [comment]
Hi, agree that a change is needed, but shouldn't the first test be against
`NSLocationAlwaysAndWhenInUseUsageDescription`
which is newly introduced in the plist?
[https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization](url)

**Comment by canado** [comment]
Hi, I am using your branch
    <plugin spec="https://github.com/Babettestam/cordova-plugin-geolocation.git" />
but the custom string for the NSLocationWhenInUseUsageDescription is still not working for me
I am also using cli 7.0.1 and 

 <platform name="ios">
        <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
            <string>my custom string</string>
        </edit-config>
    </platform>

Any suggestions ?

**Comment by NiklasMerz** [comment]
I am setting a description via the variable GEOLOCATION_USAGE_DESCRIPTION. If you understand the warning correctly Apple now requires apps with location access to set both decriptions.  

After uploading the app to the app store apple sent an email with this warning:

> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."

**Comment by breautek** [comment]
Upon testing this PR doesn't appear to be working quite as intended.

While it does go to `[self.locationManager  requestAlwaysAuthorization];` if the plist keys are set appropriately, requesting always authorization is only valid if the app already has when in use granted. Otherwise, this API call behaves as if you're calling requestWhenInUseAuthorization

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization?language=objc

This kind of flow will make it difficult to actually support "always" state while maintaining the W3C geolocation API specification, which doesn't actually support/declare how to support background use.

**Pull request closed without merging**
