### PR TITLE
Add required=false to the uses-feature

### PR DESCRIPTION
**Pull request by ochakov**
### Platforms affected
Android

### What does this PR do?
Modifies plugin.xml to allow installation of applications using this plugin on devices without GPS

### What testing has been done on this change?
Complete test

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-geolocation/pull/86/commits/adf3eac639d4fcb07fdc355afa5dc395b559a45d)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/30//PLATFORM=android/artifact/) |

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-geolocation/pull/86/commits/b16ed2ae886c14527de15d20c037a39a3d166f4f)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/31//PLATFORM=android/artifact/) |

**Comment by patrickbussmann** [comment]
You can add this line to your `config.xml`.

    <hook type="before_compile" src="hooks/before_compile/change_required_features_to_optional.js" />

With this content.

  #!/usr/bin/env node
  
  module.exports = function (context) {
    var
      Q = context.requireCordovaModule('q'),
      deferral = new Q.defer(),
      fs = context.requireCordovaModule('fs'),
      path = context.requireCordovaModule('path'),
      platformRoot = path.join(context.opts.projectRoot, 'platforms/android'),
      manifestFile = path.join(platformRoot, 'AndroidManifest.xml')
    ;
  
    if (fs.existsSync(manifestFile)) {
      fs.readFile(manifestFile, 'utf8', function (err, data) {
        if (err) {
          deferral.resolve();
          throw new Error('Unable to find AndroidManifest.xml: ' + err);
        }
  
        fs.writeFile(manifestFile, (function (str) {
          str = str.replace(/android:required="true"/ig, 'android:required="false"');
          str = str.replace(/<uses-feature android:name="([^"]+)" ?\/>/ig, '<uses-feature android:name="$1" android:required="false" />');
          return str;
        })(data), 'utf8', function (err) {
          deferral.resolve();
          if (err) throw new Error('Unable to write into AndroidManifest.xml: ' + err);
        });
      });
    } else {
      deferral.resolve();
    }
  
    return deferral.promise;
  };

Then it will work fine and you will have no more dependencies :+1: 

But yes your pull request should be merged as soon as possible :+1:

**Comment by ochakov** [comment]
@patrickbussmann the workaround with the hook will create duplicate uses line in AndroidManifest.xml if you have another plugin declaring the same uses with required false.

**Comment by andreujuanc** [comment]
@patrickbussmann Any news on this? As of now I have to manually change the plugin's file

**Comment by precz** [comment]
Hi, this somehow should be and option in plugin. For now you could add this line to `config.xml` under `widget`:
```
<edit-config file="AndroidManifest.xml" target="/manifest/uses-feature[@android:name='android.hardware.location.gps']" mode="overwrite">
      <uses-feature android:name="android.hardware.location.gps" android:required="false"/>
</edit-config>
```
**It will work only for the first time, unfortunately. Every next run you need to remove duplicated key from `platforms/android/app/src/main/AndroidManifest.xml`.**

**Comment by hvaughan3** [comment]
@precz We use the [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) plugin without issue:

    <custom-config-file parent="/*" target="AndroidManifest.xml">
        <uses-feature android:name="android.hardware.location" android:required="false" />
        <uses-feature android:name="android.hardware.location.network" android:required="false" />
    </custom-config-file>

**Comment by Saturnyn** [comment]
Hi, do you have any news on this ? I have the same problem with my app and could not figure out why some customers weren't able to install it until I saw this.

**Comment by janpio** [comment]
Noone in here really explained what exactly the problem is that this changes solves - could someone please explain when this is useful and why? How does the plugin work without GPS being present?

**Comment by breautek** [comment]
> Noone in here really explained what exactly the problem is that this changes solves - could someone please explain when this is useful and why? How does the plugin work without GPS being present?

In Android Manifest, if the app is defined to use the GPS feature, and it has `required=true` then that tells Google that the phone _must_ have GPS hardware on their phone to use the app.

`required=false` will allow the app to be installed on an android device without GPS hardware, which allows apps to be more flexible, such as supporting customers without GPS hardware, but provide a better experience for users who do have GPS hardware under the same app. Obviously the app itself would have to determine if GPS hardware is available before using GPS features.

**Comment by janpio** [comment]
Ok, so this change would let those apps _include_ the plugin, but of course still not (in any useful way) use it - that would then have to be handled by the developer manually. Correct?

**Comment by breautek** [comment]
Correct. When a feature is marked as required. It signals that the app cannot function without that feature. When the feature is marked as not required, it says the app will use the feature, if available on the device.

**Comment by breautek** [comment]
I personally wouldn't hard code true or false for this value. This should be a configurable option based on the developers requirements.

**Comment by andreszs** [comment]
I've created a new PR #171 with an **ANDROID_GPS_REQUIRED** parameter, so the requirement (true/false) can be set when installing the plugin. Please endorse the PR so it gets merged soon, thanks. Tested with cordova@7.1.0 and cordova-android@6.3.0.

**Comment by baltar** [comment]
> Ok, so this change would let those apps include the plugin, but of course still not (in any useful way) use it.

Actually this is not completely correct, there are other locationing methods such as network-based, which might be less precise but still often sufficient for most apps, or at least better than nothing.

**Pull request closed without merging**
