### PR TITLE
Add missing module references for Android

### PR DESCRIPTION
**Pull request by fredtitao**

### CODE REVIEW

**Comment by timuric** [comment]
Can you please merge this request, otherwise plugin does not install on android

**Comment by digiclick74** [comment]
Sorry but I don't have the permissions to merge the pull request.

**Comment by jcesarmobile** [comment]
Android geolocation plugin code doesn't exist anymore, it just uses the HTML 5 geolocation API, so nothing has to be copied to the platform folder to make the plugin work, just the androidManifest permissions.

**Comment by infil00p** [comment]
Just as @jcesarmobile said, there are no modules needed, therefore this should be closed.  Because this is a copy of the repository, and not the repository itself, I can't close this one from here.

**Pull request closed without merging**
