### PR TITLE
CB-10286 Don't skip automatic tests on Android devices

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-10286

### CODE REVIEW

**Comment by sgrebnov** [comment]
:+1: lgtm

**Comment by sgrebnov** [comment]
Actually, starting from Android M we now have Permissions prompt dialog so those tests can't be run in silent mode so we should skip them as well.

**Comment by alsorokin** [comment]
@sgrebnov I've just added the check for Android >= 6.0

**Comment by sgrebnov** [comment]
:+1:

**Pull request closed without merging**
