### PR TITLE
CB-7754 - [Geolocation] Support Background Location tracking

### PR DESCRIPTION
**Pull request by shazron**

### CODE REVIEW

**Comment by michaelkrog** [comment]
@shazron can you helpt me out? 

I'm a bit confused. Does cordova-plugin-geolocation currently have background location support or does it not?

**Comment by shazron** [comment]
The plugin supports geolocation tracking on iOS 8 only when the app is in use. To use it when the app is in the background, you need to install the plugin above.

**Comment by sandstrom** [comment]
Any existing value for `NSLocationAlwaysUsageDescription ` in the plist gets overwritten with an empty string. This makes it harder to provide a custom description (which is the purpose of the string, btw).

Don't know if the plugin facility allows, but if it could handle this 'softly', e.g. only add the key to the plist unless it already exists, that would solve it.

**Comment by Zorgatone** [comment]
Any news about this? Is the issue only about iOS? Does it work in background with other platforms?

Can I use background location on the available platforms with this plugin (with iOS fix)?

**Comment by MrMotski** [comment]
Is there any update to @Zorgatone's question? I'm also very interested to know the answer.

**Comment by purplecabbage** [comment]
iOS only. See the issue in JIRA : https://issues.apache.org/jira/browse/CB-7754

**Comment by diegobill** [comment]
+1

I'm also very interested in Android and iOS support.

**Comment by kamendo** [comment]
I tried

> cordova plugin add https://github.com/apache/cordova-plugin-geolocation.git#master:src/ios/background-location

but failed with this error:
'support for subdirectories is deprecated and will be removed in Cordova@7
Error: --fetch does not support subdirectories'

**Comment by shazron** [comment]
@kamendo You'll just have to download the plugin and install it by folder path for now. Cordova@7 dropped support for sub-folders and the plugin has to be migrated

**Comment by kamendo** [comment]
@shazron, just FYI - I ended up adding a custom plugin and swizzle the iOS method in order to get the location working in background :)

 https://github.com/stefanminch/background-location-app/blob/master/src/ios/BackgroundProcess.m

**Comment by janpio** [comment]
`src/ios/background-location` is gone, so I think this PR doesn't make any sense any more :(

**Pull request closed without merging**
