### PR TITLE
background location under iOS 9

### PR DESCRIPTION
**Pull request by ccloquet**
Hi, 

Thanks for this upgrade of the plugin !

I just tried to run in under iOS 9, and it seems that the following lines should be added before [self.locationManager startUpdatingLocation] : 

```
locationManager.pausesLocationUpdatesAutomatically = NO;
locationManager.allowsBackgroundLocationUpdates = YES;
```

However, doing so drains the battery quickly.

Do you have a similar experience ?

These lines can also be useful, even not strictly necessary for the background usage : 

```
locationManager.activityType = CLActivityTypeFitness;
locationManager.desiredAccuracy = kCLLocationAccuracyBestForNavigation;
locationManager.distanceFilter = kCLDistanceFilterNone;
```

### CODE REVIEW

**Comment by andreyzenkov** [comment]
Hey guys. This fix really need.

**Comment by mauron85** [comment]
Can I ask, why is this still not merged? Cordova 6 is out, declaring new versions also of this plugin, but background locations are not working on iOS9. Guys we need this. Thank you

**Comment by alejandromagnorsky** [comment]
I confirm that THIS plugin unexpectedly disabled another background geolocation plugin I'm using.
But @mauron85 fork (cordova-plugin-geolocation-ios9-fix) fixs it. So, please, if this pull request is equivalent to the fork, go for it since I need this update.
Thanks.

**Comment by alejandromagnorsky** [comment]
+1

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-geolocation/pull/51/commits/b9e5fdf9fb54c31e292c034aa7e52fd615b12e7c)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-geolocation-pr/2//label=mac-slave,platformName=android/artifact/) |

**Comment by ssgtcookie** [comment]
How about iOS 10 beta, anyone tested this?

**Comment by ctcampbell** [comment]
Yep, works fine for me.

**Comment by Freundschaft** [comment]
when will this be merged?

**Comment by thelucre** [comment]
Has this been merged yet?

**Comment by lincolnthree** [comment]
Any updates on this PR? Looks like it (at one point) was cleanly built and ready to go.

**Comment by breautek** [comment]
Closing because iOS 9 is obsolete.

**Pull request closed without merging**
